Repository AY2324S2-CS2103T-W11-2/tp, pull requests merged in 2024-04, with the labels that each got.

#109 Implement displaying of CCA
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CcaCard.java
  src/main/java/seedu/address/ui/DisplayObjectListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/CcaListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DisplayObjectListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#113 Add ability to filer by CCA and roles
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/CcaContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/RoleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/AssignPersonDescriptorBuilder.java
Labels: enhancement

#117 Implement delete cca command
  src/main/java/seedu/address/logic/commands/DeleteCcaCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCcaCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/CcaContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, story

#111 Add a set attendance feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/OweCommand.java
  src/main/java/seedu/address/logic/commands/SetAttCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetAttCommandParser.java
  src/main/java/seedu/address/model/attendance/Attendance.java
  src/main/java/seedu/address/model/attendance/Sessions.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SetAttCommandTest.java
  src/test/java/seedu/address/logic/parser/SetAttCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/SetAttDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, story

#179 Fix metadata null exceptions
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/OweCommand.java
  src/main/java/seedu/address/logic/commands/SetAttCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Metadata.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug

#180 Change help URL to CCA Manager
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: bug

#183 Fix removal of CCA when no more members in CCA
  src/main/java/seedu/address/logic/commands/DeleteCcaCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/ui/CcaCard.java
Labels: bug

#184 Fix result messages and error messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ChargeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCcaCommand.java
  src/main/java/seedu/address/logic/commands/SetAttCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/ChargeCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCcaCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/OweCommandParser.java
  src/main/java/seedu/address/logic/parser/SetAttCommandParser.java
  src/main/java/seedu/address/model/person/CcaContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OweCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetAttCommandParserTest.java
Labels: bug

#186 Change `r/` and `c/` as a way to clear the fields to `r/nil` and `c/nil`
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/cca/Cca.java
  src/main/java/seedu/address/model/roles/Role.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug

#189 Fix sample data and added text wrap to UI so that I can do the screenshots for UG
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: bug, enhancement

#192 WIP User Guide
  docs/UserGuide.md
  docs/UserGuide.md.old
  docs/images/Ui.png
  docs/images/addcommandoutcome.png
  docs/images/editcommandoutcome1.png
  docs/images/editcommandoutcome2.png
  docs/images/helpMessage.png
  docs/images/listcommandoutcome.png
  docs/stylesheets/main.css
Labels: documentation

#193 Fix broken link detector
  docs/UserGuide.md
Labels: documentation

#188 Fix multiple issues
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ChargeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCcaCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/OweCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ChargeCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCcaCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/OweCommandParser.java
Labels: bug

#194 Fix the email domain bug
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/logic/commands/OweCommandTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: bug

#195 Fix Name Accepting Numbers
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: bug

#197 Partially filled command formats
  docs/UserGuide.md
Labels: documentation

#202 Fix/phone validator
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug

#200 Added navigation links throughout the UG
  docs/UserGuide.md
Labels: documentation

#204 Removed Ability to Assign Role for Add, Assign and Edit Commands without CCA
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ChargeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCcaCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SetAttCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#205 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UG-Basics/outcomeClearAfter.png
  docs/images/UG-Basics/outcomeClearBefore.png
  docs/images/UG-Basics/outcomeDeleteAfter.png
  docs/images/UG-Basics/outcomeDeleteBefore.png
Labels: documentation

#208 Rename addressbook.json to ccamanager.json
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: bug

#206 Improve formatting (mostly)
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: documentation

#209 Change Assign to Append
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
Labels: bug

#213 Edit Command Automatically Removes Roles when a CCAs are also removed from a Contact
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: bug

#216 Update UG to Reflect Roles not Being Applicable for People without CCA
  docs/UserGuide.md
Labels: documentation

#219 Finalise UG
  docs/UserGuide.md
Labels: documentation

#220 Fix warnings from AssignCommand
  src/main/java/seedu/address/logic/commands/AssignCommand.java
Labels: bug

#223 Fix DG To Say CCA Manager instead of AB3 Addressbook
  docs/DeveloperGuide.md
Labels: documentation

#224 Fix find command screenshot
  docs/UserGuide.md
  docs/images/UG-Basics/filter-output-1.png
  docs/images/UG-Basics/find-output-1.png
  docs/images/UG-Basics/outcomeCca_deleteAfter1.png
  docs/images/editcommandoutcome2.png
  docs/images/listcommandoutcome.png
Labels: documentation
