Repository AY2324S2-CS2103T-W11-2/tp, pull requests merged in 2024-03, with the labels that each got.

#24 Update small change on UserGuide.md to meet with tp Dashboard
  docs/UserGuide.md
Labels: documentation

#22 Add Ken Jin's profile picture
  docs/AboutUs.md
  docs/images/fidget-spinner.jpg
Labels: documentation

#16 Update glossary
  docs/DeveloperGuide.md
Labels: documentation

#21 Remove Lifu's JPG photo
  docs/AboutUs.md
  docs/images/lifhoshi.jpg
Labels: documentation

#26 Add Jae Geun's Profile Picture
  docs/AboutUs.md
  docs/images/alphajae11.png
Labels: documentation

#28 Rename Ken Jin's JPG to PNG
  docs/AboutUs.md
  docs/images/fidget-spinner.png
Labels: documentation

#27 Update AboutUs
  docs/AboutUs.md
  docs/images/chuahjiajie.png
Labels: documentation

#23 Update README for CCA Manager details
  README.md
Labels: documentation

#31 Remove AB3 from user guide
  docs/UserGuide.md
Labels: documentation

#32 Add "title:" Back to Heading
  docs/AboutUs.md
Labels: documentation

#17 Update non-functional requirements.
  docs/DeveloperGuide.md
Labels: documentation

#57 Fix StorageClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation

#71 Partially revert 1213e98
  docs/UserGuide.md
Labels: documentation

#73 Explain target audience prerequisite knowledge
  docs/UserGuide.md
Labels: documentation

#74 Add an introduction to the UG
  docs/UserGuide.md
Labels: documentation

#75 Adds FAQ questions in UG
  docs/UserGuide.md
Labels: documentation

#76 Add Basics Section to UG
  docs/UserGuide.md
  docs/images/UG-Basics/add-command-1.png
  docs/images/UG-Basics/add-command-2.png
  docs/images/UG-Basics/add-output-1.png
  docs/images/UG-Basics/add-output-2.png
  docs/images/UG-Basics/assign-command.png
  docs/images/UG-Basics/assign-output.png
  docs/images/UG-Basics/clear-command.png
  docs/images/UG-Basics/clear-output.png
  docs/images/UG-Basics/delete-command.png
  docs/images/UG-Basics/delete-output.png
  docs/images/UG-Basics/edit-command.png
  docs/images/UG-Basics/edit-output.png
  docs/images/UG-Basics/filter-command-1.png
  docs/images/UG-Basics/filter-command-2.png
  docs/images/UG-Basics/filter-output-1.png
  docs/images/UG-Basics/filter-output-2.png
Labels: documentation

#77 Fix UserGuide.md
  docs/UserGuide.md
Labels: documentation

#81 Add small gloassary and os-specific info
  docs/UserGuide.md
Labels: documentation

#82 Edits the UG up till Tutorials
  docs/UserGuide.md
  docs/images/CommandLine.png
  docs/images/Ui.png
  docs/stylesheets/main.css
Labels: documentation

#84 Style print navbar in UG
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: documentation

#93 Refactor from tag to role and fix many issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/cca/Cca.java
  src/main/java/seedu/address/model/person/CcaContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/roles/Role.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCCA.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/cca/CcaTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RoleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/role/RoleTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/AssignPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: Refactor

#98 Update DeveloperGuide with payment splitting
  docs/DeveloperGuide.md
Labels: documentation

#99 Update DG with Attendance Tracking
  docs/DeveloperGuide.md
Labels: documentation

#104 Implement UniqueCcaList and updated the DG
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/cca/Cca.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniqueCcaList.java
  src/main/java/seedu/address/model/person/exceptions/CcaNotFoundException.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateCcaException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement
